sudo: false
language: node_js
node_js:
  - "8"
  - "6"
  - "4"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
env:
  - CXX=g++-4.8

install:
  # install modules
  - yarn install --ignore-scripts
  # build
  - prebuild --strip

before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
